export default {
  applicantMap : {
    "form1[0].#subform[0].PtAILine1_ANumber[0]" : "foreignNumber",
    "form1[0].#subform[0].TextField1[0]" : "socialSecurityNumber",
    "form1[0].#subform[0].PtAILine4_LastName[0]" : "lastName",
    "form1[0].#subform[0].PtAILine5_FirstName[0]" : "firstName",
    "form1[0].#subform[0].PtAILine6_MiddleName[0]" : "middleName",
    "form1[0].#subform[0].TextField1[1]" : "otherName",
    "form1[0].#subform[0].PtAILine8_StreetNumandName[0]" : "street",
    "form1[0].#subform[0].PtAILine8_AptNumber[0]" : "apartment",
    "form1[0].#subform[0].TextField1[2]" : "city",
    "form1[0].#subform[0].PtAILine8_State[0]" : "state",
    "form1[0].#subform[0].PtAILine8_Zipcode[0]" : "postalCode",
    "form1[0].#subform[0].DateTimeField1[0]" : "birthday",
    "form1[0].#subform[0].TextField1[4]" : "birthPlace",
    "form1[0].#subform[0].TextField1[3]" : "presentNationality",
    "form1[0].#subform[0].TextField1[5]" : "nationalityAtBirth",
    "form1[0].#subform[0].TextField5[0]" : "passportCountry",
    "form1[0].#subform[0].TextField5[1]" : "passportNumber",
    "form1[0].#subform[0].DateTimeField2[1]" : "statusExpirationDate",
    "form1[0].#subform[0].DateTimeField2[2]" : "expirationOfPassport",
    "form1[0].#subform[0].TextField7[0]" : "nativeLanguage",
    "form1[0].#subform[0].TextField7[1]" : "otherLanguages",
    "form1[0].#subform[0].PartALine9Gender[0]" : "male",
    "form1[0].#subform[0].PartALine9Gender[1]" : "female",
    "form1[0].#subform[0].Marital[0]" : "single",
    "form1[0].#subform[0].Marital[1]" : "married",
    "form1[0].#subform[0].Marital[2]" : "divorced",
    "form1[0].#subform[0].Marital[3]" : "widowed",
    "form1[0].#subform[0].CheckBox3[0]" : "courtProcessOption1",
    "form1[0].#subform[0].CheckBox3[2]" : "courtProcessOption2",
    "form1[0].#subform[0].CheckBox3[1]" : "courtProcessOption3",
    "form1[0].#subform[0].CheckBox4[0]" : "yesEnglish",
    "form1[0].#subform[0].CheckBox4[1]" : "noEnglish",
    "form1[0].#subform[1].CheckBox5[0]" : "noMarried",
    "form1[0].#subform[0].PtAILine8_AreaCode[0]" : "areaCode",
    "form1[0].#subform[0].PtAILine8_TelephoneNumber[0]" : "phoneNumber",
    "form1[0].#subform[0].TextField1[6]" : "race",
    "form1[0].#subform[0].TextField1[7]" : "religion",
    "form1[0].#subform[0].DateTimeField6[0]" : "lastLeaveCountry",
    "form1[0].#subform[0].TextField3[0]" : "i94Number",
    "form1[0].#subform[1].ChildrenCheckbox[0]" : "yesHasKids",
    "form1[0].#subform[1].TotalChild[0]" : "numberOfKids",
    "form1[0].#subform[1].ChildrenCheckbox[1]" : "noHaveKids",
    "form1[0].#subform[4].CheckBoxAIII5\\.m[0]" : "motherDead",
    "form1[0].#subform[4].CheckBoxAIII5\\.f[0]" : "fatherDead",
    "form1[0].#subform[13].TextField32[0]" : "extraSiblingsField",
    "form1[0].#subform[13].TextField31[1]": "question",
    "form1[0].#subform[13].TextField31[0]": "part",
  },

  arrayMap : {
    "form1[0].#subform[0].DateTimeField2[0]": ["americanEntranceList", 0, "date"],
    "form1[0].#subform[0].TextField4[0]": ["americanEntranceList", 0, "place"],
    "form1[0].#subform[0].TextField4[1]": ["americanEntranceList", 0, "status"],
    "form1[0].#subform[0].DateTimeField3[0]": ["americanEntranceList", 1, "date"],
    "form1[0].#subform[0].TextField4[2]": ["americanEntranceList", 1, "place"],
    "form1[0].#subform[0].TextField4[3]": ["americanEntranceList", 1, "status"],
    "form1[0].#subform[0].DateTimeField4[0]": ["americanEntranceList", 2, "date"],
    "form1[0].#subform[0].TextField4[4]": ["americanEntranceList", 2, "place"],
    "form1[0].#subform[0].TextField4[5]": ["americanEntranceList", 2, "status"],
    "form1[0].#subform[4].TextField13[0]" : ["foreignAddress", 0, "address"],
    "form1[0].#subform[4].TextField13[2]" : ["foreignAddress", 0, "city"],
    "form1[0].#subform[4].TextField13[4]" : ["foreignAddress", 0, "state"],
    "form1[0].#subform[4].TextField13[6]" : ["foreignAddress", 0, "country"],
    "form1[0].#subform[4].DateTimeField21[0]" : ["foreignAddress", 0, "from"],
    "form1[0].#subform[4].DateTimeField20[0]" : ["foreignAddress", 0, "to"],
    "form1[0].#subform[4].TextField13[1]" : ["foreignAddress", 1, "address"],
    "form1[0].#subform[4].TextField13[3]" : ["foreignAddress", 1, "city"],
    "form1[0].#subform[4].TextField13[5]" : ["foreignAddress", 1, "state"],
    "form1[0].#subform[4].TextField13[7]" : ["foreignAddress", 1, "country"],
    "form1[0].#subform[4].DateTimeField22[0]" : ["foreignAddress", 1, "from"],
    "form1[0].#subform[4].DateTimeField23[0]" : ["foreignAddress", 1, "to"],
    "form1[0].#subform[4].TextField13[8]" : ["residentAddress", 0, "address"],
    "form1[0].#subform[4].TextField13[10]" : ["residentAddress", 0, "city"],
    "form1[0].#subform[4].TextField13[12]" : ["residentAddress", 0, "state"],
    "form1[0].#subform[4].TextField13[14]" : ["residentAddress", 0, "country"],
    "form1[0].#subform[4].DateTimeField24[0]" : ["residentAddress", 0, "from"],
    "form1[0].#subform[4].DateTimeField26[0]" : ["residentAddress", 0, "to"],
    "form1[0].#subform[4].TextField13[9]" : ["residentAddress", 1, "address"],
    "form1[0].#subform[4].TextField13[11]" : ["residentAddress", 1, "city"],
    "form1[0].#subform[4].TextField13[13]" : ["residentAddress", 1, "state"],
    "form1[0].#subform[4].TextField13[15]" : ["residentAddress", 1, "country"],
    "form1[0].#subform[4].DateTimeField25[0]" : ["residentAddress", 1, "from"],
    "form1[0].#subform[4].DateTimeField27[0]" : ["residentAddress", 1, "to"],
    "form1[0].#subform[4].TextField13[16]" : ["residentAddress", 2, "address"],
    "form1[0].#subform[4].TextField13[17]" : ["residentAddress", 2, "city"],
    "form1[0].#subform[4].TextField13[18]" : ["residentAddress", 2, "state"],
    "form1[0].#subform[4].TextField13[19]" : ["residentAddress", 2, "country"],
    "form1[0].#subform[4].DateTimeField28[0]" : ["residentAddress", 2, "from"],
    "form1[0].#subform[4].DateTimeField29[0]" : ["residentAddress", 2, "to"],
    "form1[0].#subform[4].TextField13[20]" : ["residentAddress", 3, "address"],
    "form1[0].#subform[4].TextField13[21]" : ["residentAddress", 3, "city"],
    "form1[0].#subform[4].TextField13[22]" : ["residentAddress", 3, "state"],
    "form1[0].#subform[4].TextField13[23]" : ["residentAddress", 3, "country"],
    "form1[0].#subform[4].DateTimeField30[0]" : ["residentAddress", 3, "from"],
    "form1[0].#subform[4].DateTimeField31[0]" : ["residentAddress", 3, "to"],
    "form1[0].#subform[4].TextField13[24]" : ["residentAddress", 4, "address"],
    "form1[0].#subform[4].TextField13[25]" : ["residentAddress", 4, "city"],
    "form1[0].#subform[4].TextField13[26]" : ["residentAddress", 4, "state"],
    "form1[0].#subform[4].TextField13[27]" : ["residentAddress", 4, "country"],
    "form1[0].#subform[4].DateTimeField32[0]" : ["residentAddress", 4, "from"],
    "form1[0].#subform[4].DateTimeField33[0]" : ["residentAddress", 4, "to"],
    "form1[0].#subform[4].TextField13[28]" : ["school", 0, "name"],
    "form1[0].#subform[4].TextField13[30]" : ["school", 0, "type"],
    "form1[0].#subform[4].TextField13[32]" : ["school", 0, "location"],
    "form1[0].#subform[4].DateTimeField41[0]" : ["school", 0, "from"],
    "form1[0].#subform[4].DateTimeField40[0]" : ["school", 0, "to"],
    "form1[0].#subform[4].TextField13[29]" : ["school", 1, "name"],
    "form1[0].#subform[4].TextField13[31]" : ["school", 1, "type"],
    "form1[0].#subform[4].TextField13[33]" : ["school", 1, "location"],
    "form1[0].#subform[4].DateTimeField38[0]" : ["school", 1, "from"],
    "form1[0].#subform[4].DateTimeField39[0]" : ["school", 1, "to"],
    "form1[0].#subform[4].TextField13[34]" : ["school", 2, "name"],
    "form1[0].#subform[4].TextField13[35]" : ["school", 2, "type"],
    "form1[0].#subform[4].TextField13[36]" : ["school", 2, "location"],
    "form1[0].#subform[4].DateTimeField37[0]" : ["school", 2, "from"],
    "form1[0].#subform[4].DateTimeField36[0]": ["school", 2, "to"],
    "form1[0].#subform[4].TextField13[37]" : ["school", 3, "name"],
    "form1[0].#subform[4].TextField13[38]" : ["school", 3, "type"],
    "form1[0].#subform[4].TextField13[39]" : ["school", 3, "location"],
    "form1[0].#subform[4].DateTimeField34[0]" : ["school", 3, "from"],
    "form1[0].#subform[4].DateTimeField35[0]" : ["school", 3, "to"],
    "form1[0].#subform[4].TextField13[40]" : ["occupation", 0, "employer"],
    "form1[0].#subform[4].TextField13[42]" : ["occupation", 0, "position"],
    "form1[0].#subform[4].DateTimeField42[0]" : ["occupation", 0, "from"],
    "form1[0].#subform[4].DateTimeField44[0]" : ["occupation", 0, "to"],
    "form1[0].#subform[4].TextField13[41]" : ["occupation", 1, "employer"],
    "form1[0].#subform[4].TextField13[43]" : ["occupation", 1, "position"],
    "form1[0].#subform[4].DateTimeField43[0]" : ["occupation", 1, "from"],
    "form1[0].#subform[4].DateTimeField45[0]" : ["occupation", 1, "to"],
    "form1[0].#subform[4].TextField13[44]" : ["occupation", 2, "employer"],
    "form1[0].#subform[4].TextField13[45]" : ["occupation", 2, "position"],
    "form1[0].#subform[4].DateTimeField46[0]" : ["occupation", 2, "from"],
    "form1[0].#subform[4].DateTimeField47[0]" : ["occupation", 2, "to"],
    "form1[0].#subform[4].TextField13[46]" : ["mother", 0, "name"],
    "form1[0].#subform[4].TextField13[49]" : ["mother", 0, "birthPlace"],
    "form1[0].#subform[4].TextField35[0]" : ["mother", 0, "location"],
    "form1[0].#subform[4].TextField13[47]" : ["father", 0, "name"],
    "form1[0].#subform[4].TextField13[50]" : ["father", 0, "birthPlace"],
    "form1[0].#subform[4].TextField35[1]" : ["father", 0, "location"],
    "form1[0].#subform[4].TextField13[48]" : ["sibling", 0, "name"],
    "form1[0].#subform[4].TextField13[51]" : ["sibling", 0, "origin"],
    "form1[0].#subform[4].TextField35[2]" : ["sibling", 0, "location"],
    "form1[0].#subform[4].CheckBoxAIII5\\.s1[0]" : ["sibling", 0, "deceased"],
    "form1[0].#subform[4].TextField13[52]" : ["sibling", 1, "name"],
    "form1[0].#subform[4].TextField13[53]" : ["sibling", 1, "origin"],
    "form1[0].#subform[4].TextField35[3]" : ["sibling", 1, "location"],
    "form1[0].#subform[4].CheckBoxAIII5\\.s2[0]" : ["sibling", 1, "deceased"],
    "form1[0].#subform[4].TextField13[54]" : ["sibling", 2, "name"],
    "form1[0].#subform[4].TextField13[55]" : ["sibling", 2, "origin"],
    "form1[0].#subform[4].TextField35[4]" : ["sibling", 2, "location"],
    "form1[0].#subform[4].CheckBoxAIII5\\.s3[0]" : ["sibling", 2, "deceased"],
    "form1[0].#subform[4].TextField13[56]" : ["sibling", 3, "name"],
    "form1[0].#subform[4].TextField13[57]" : ["sibling", 3, "origin"],
    "form1[0].#subform[4].TextField35[5]" : ["sibling", 3, "location"],
    "form1[0].#subform[4].CheckBoxAIII5\\.s4[0]" : ["sibling", 3, "deceased"],
  },

  spouseMap : {
    "form1[0].#subform[1].NotMarried[0].PtAIILine1_ANumber[0]" : "foreignNumber",
    "form1[0].#subform[1].NotMarried[0].TextField10[1]" : "passportNumber",
    "form1[0].#subform[1].NotMarried[0].DateTimeField7[0]" : "birthday",
    "form1[0].#subform[1].NotMarried[0].TextField10[2]" : "socialSecurityNumber",
    "form1[0].#subform[1].NotMarried[0].PtAIILine5_LastName[0]" : "lastName",
    "form1[0].#subform[1].NotMarried[0].PtAIILine6_FirstName[0]" : "firstName",
    "form1[0].#subform[1].NotMarried[0].PtAIILine7_MiddleName[0]" : "middleName",
    "form1[0].#subform[1].NotMarried[0].TextField10[3]" : "otherName",
    "form1[0].#subform[1].NotMarried[0].DateTimeField8[0]" : "marriageDate",
    "form1[0].#subform[1].NotMarried[0].TextField10[4]" : "marriagePlace",
    "form1[0].#subform[1].NotMarried[0].TextField10[5]" : "birthPlace",
    "form1[0].#subform[1].NotMarried[0].TextField10[0]" : "presentNationality",
    "form1[0].#subform[1].NotMarried[0].PtAIILine16_PlaceofLastEntry[0]" : "lastEntryPlace",
    "form1[0].#subform[1].NotMarried[0].PtAIILine17_DateofLastEntry[0]" : "lastEntryDate",
    "form1[0].#subform[1].NotMarried[0].PtAIILine18_I94Number[0]" : "i94Number",
    "form1[0].#subform[1].NotMarried[0].PtAIILine19_StatusofLastAdmission[0]" : "lastEntryStatus",
    "form1[0].#subform[1].NotMarried[0].PtAIILine20_SpouseCurrentStatus[0]" : "currentStatus",
    "form1[0].#subform[1].NotMarried[0].PtAIILine15_Specify[0]" : "currentLocation",
    "form1[0].#subform[1].NotMarried[0].PtAIILine21_ExpDateofAuthorizedStay[0]" : "statusExpirationDate",
    "form1[0].#subform[1].NotMarried[0].PtAIILine23_PreviousArrivalDate[0]" : "dateOfPreviousEntry",
    "form1[0].#subform[1].NotMarried[0].CheckBox14_Gender[0]" : "male",
    "form1[0].#subform[1].NotMarried[0].CheckBox14_Gender[1]" : "female",
    "form1[0].#subform[1].NotMarried[0].PtAIILine15_CheckBox15[1]" : "yesInAmerica",
    "form1[0].#subform[1].NotMarried[0].PtAIILine15_CheckBox15[0]" : "noInAmerica",
    "form1[0].#subform[1].NotMarried[0].PtAIILine22_Yes[0]" : "yesCourtProceedings",
    "form1[0].#subform[1].NotMarried[0].PtAIILine22_No[0]" : "noCourtProceedings",
    "form1[0].#subform[1].NotMarried[0].PtAIILine24_Yes[0]" : "yesInclude",
    "form1[0].#subform[1].NotMarried[0].PtAIILine24_No[0]" : "noInclude",
    "form1[0].#subform[1].NotMarried[0].TextField10[6]" : "race",
  },

  asylumMap : {
    "form1[0].#subform[5].#subform[6].TextField14[0]" : "B1A",
    "form1[0].#subform[5].#subform[6].TextField15[0]" : "B1B",
    "form1[0].#subform[7].PBL2_TextField[0]" : "B2",
    "form1[0].#subform[7].PBL3A_TextField[0]" : "B3A",
    "form1[0].#subform[7].PBL3B_TextField[0]" : "B3B",
    "form1[0].#subform[7].PB4_TextField[0]" : "B4",
    "form1[0].#subform[8].PCL1_TextField[0]" : "C1",
    "form1[0].#subform[8].PCL2B_TextField[0]" : "C2B",
    "form1[0].#subform[8].PCL3_TextField[0]" : "C3",
    "form1[0].#subform[9].PCL4_TextField[0]" : "C4",
    "form1[0].#subform[9].PCL5_TextField[0]" : "C5",
    "form1[0].#subform[9].PCL6_TextField[0]" : "C6",
    "form1[0].#subform[5].#subform[6].CheckBoxrace[0]" : "race",
    "form1[0].#subform[5].#subform[6].CheckBoxreligion[0]" : "religion",
    "form1[0].#subform[5].#subform[6].CheckBoxnationality[0]" : "nationality",
    "form1[0].#subform[5].#subform[6].CheckBoxpolitics[0]" : "politicalOpinion",
    "form1[0].#subform[5].#subform[6].CheckBoxsocial[0]" : "group",
    "form1[0].#subform[5].#subform[6].CheckBoxtorture[0]" : "torture",
    "form1[0].#subform[5].#subform[6].ckboxyn1a[1]" : "b1aNo",
    "form1[0].#subform[5].#subform[6].ckboxyn1a[0]" : "b1aYes",
    "form1[0].#subform[5].#subform[6].ckboxyn1b[1]" : "b1bNo",
    "form1[0].#subform[5].#subform[6].ckboxyn1b[0]" : "b1bYes",
    "form1[0].#subform[7].ckboxyn2[1]" : "b2No",
    "form1[0].#subform[7].ckboxyn2[0]" : "b2Yes",
    "form1[0].#subform[7].ckboxyn3a[1]" : "b3aNo",
    "form1[0].#subform[7].ckboxyn3a[0]" : "b3aYes",
    "form1[0].#subform[7].ckboxyn3b[1]" : "b3bNo",
    "form1[0].#subform[7].ckboxyn3b[0]" : "b3bYes",
    "form1[0].#subform[7].ckboxyn4[1]" : "b4No",
    "form1[0].#subform[7].ckboxyn4[0]" : "b4Yes",
    "form1[0].#subform[8].ckboxync1[1]" : "c1No",
    "form1[0].#subform[8].ckboxync1[0]" : "c1Yes",
    "form1[0].#subform[8].ckboxync2a[1]" : "c2aNo",
    "form1[0].#subform[8].ckboxync2a[0]" : "c2aYes",
    "form1[0].#subform[8].ckboxync2b[1]" :  "c2bNo",
    "form1[0].#subform[8].ckboxync2b[0]" : "c2bYes",
    "form1[0].#subform[8].ckboxync3[1]" : "c3No",
    "form1[0].#subform[8].ckboxync3[0]" : "c3Yes",
    "form1[0].#subform[9].PCckboxyn4[1]" : "c4No",
    "form1[0].#subform[9].PCckboxyn4[0]" : "c4Yes",
    "form1[0].#subform[9].ckboxync5[1]" : "c5No",
    "form1[0].#subform[9].ckboxync5[0]" : "c5Yes",
    "form1[0].#subform[9].ckboxync6[1]" : "c6No",
    "form1[0].#subform[9].ckboxync6[0]" : "c6Yes",
  },

  kidsMap : {
    "form1[0].#subform[1].ChildAlien1[0]" : [0, "foreignNumber"],
    "form1[0].#subform[1].ChildPassport1[0]" : [0, "passportNumber"],
    "form1[0].#subform[1].ChildMarital1[0]" : [0, "maritalStatus"],
    "form1[0].#subform[1].ChildSSN1[0]" : [0, "socialSecurityNumber"],
    "form1[0].#subform[1].ChildLast1[0]" : [0, "lastName"],
    "form1[0].#subform[1].ChildFirst1[0]" : [0, "firstName"],
    "form1[0].#subform[1].ChildMiddle1[0]" : [0, "middleName"],
    "form1[0].#subform[1].ChildDOB1[0]" : [0, "birthday"],
    "form1[0].#subform[1].ChildCity1[0]" : [0, "birthPlace"],
    "form1[0].#subform[1].ChildNat1[0]" : [0, "presentNationality"],
    "form1[0].#subform[1].ChildRace1[0]" : [0, "race"],
    "form1[0].#subform[1].PtAIILine13_Specify[0]" : [0, "currentLocation"],
    "form1[0].#subform[1].PtAIILine14_PlaceofLastEntry[0]" : [0, "lastEntryPlace"],
    "form1[0].#subform[1].PtAIILine15_ExpirationDate[0]" : [0, "lastEntryDate"],
    "form1[0].#subform[1].PtAIILine16_I94Number[0]" : [0, "i94Number"],
    "form1[0].#subform[1].PtAIILine17_StatusofLastAdmission[0]" : [0, "lastEntryStatus"],
    "form1[0].#subform[1].PtAIILine18_CurrentStatusofChild[0]" : [0, "currentStatus"],
    "form1[0].#subform[1].PtAIILine19_ExpDateofAuthorizedStay[0]" : [0, "statusExpirationDate"],
    "form1[0].#subform[1].CheckBox16[0]" : [0, "male"],
    "form1[0].#subform[1].CheckBox16[1]" : [0, "female"],
    "form1[0].#subform[1].CheckBox17[0]" : [0, "yesInAmerica"],
    "form1[0].#subform[1].CheckBox17[1]" : [0, "noInAmerica"],
    "form1[0].#subform[1].PtAIILine21_Yes[0]" : [0, "yesInclude"],
    "form1[0].#subform[1].PtAIILine21_No[0]" : [0, "noInclude"],
    "form1[0].#subform[1].PtAIILine20_Yes[0]" : [0, "yesInCourtProcess"],
    "form1[0].#subform[1].PtAIILine20_No[0]" : [0, "noInCourtProcess"],
    "form1[0].#subform[3].ChildAlien2[0]" : [1, "foreignNumber"],
    "form1[0].#subform[3].ChildPassport2[0]" : [1, "passportNumber"],
    "form1[0].#subform[3].ChildMarital2[0]" : [1, "maritalStatus"],
    "form1[0].#subform[3].ChildSSN2[0]" : [1, "socialSecurityNumber"],
    "form1[0].#subform[3].ChildLast2[0]": [1, "lastName"],
    "form1[0].#subform[3].ChildFirst2[0]" : [1, "firstName"],
    "form1[0].#subform[3].ChildMiddle2[0]" : [1, "middleName"],
    "form1[0].#subform[3].ChildDOB2[0]" : [1, "birthday"],
    "form1[0].#subform[3].ChildCity2[0]" : [1, "birthPlace"],
    "form1[0].#subform[3].ChildNat2[0]" : [1, "presentNationality"],
    "form1[0].#subform[3].ChildRace2[0]" : [1, "race"],
    "form1[0].#subform[3].PtAIILine13_Specify2[0]" : [1, "currentLocation"],
    "form1[0].#subform[3].PtAIILine14_PlaceofLastEntry2[0]" : [1, "lastEntryPlace"],
    "form1[0].#subform[3].PtAIILine15_DateofLastEntry2[0]" : [1, "lastEntryDate"],
    "form1[0].#subform[3].PtAIILine16_I94Number2[0]" : [1, "i94Number"],
    "form1[0].#subform[3].PtAIILine17_StatusofLastAdmission2[0]" : [1, "lastEntryStatus"],
    "form1[0].#subform[3].PtAIILine18_ChildCurrentStatus2[0]" : [1, "currentStatus"],
    "form1[0].#subform[3].PtAIILine19_ExpDateofAuthorizedStay2[0]" : [1, "statusExpirationDate"],
    "form1[0].#subform[3].CheckBox26_Gender[0]" : [1, "male"],
    "form1[0].#subform[3].CheckBox26_Gender[1]" : [1, "female"],
    "form1[0].#subform[3].CheckBox27[0]" : [1, "yesInAmerica"],
    "form1[0].#subform[3].CheckBox27[1]" : [1, "noInAmerica"],
    "form1[0].#subform[3].PtAIILine21_Yes2[0]" : [1, "yesInclude"],
    "form1[0].#subform[3].PtAIILine21_No2[0]" : [1, "noInclude"],
    "form1[0].#subform[3].PtAIILine20_Yes2[0]" : [1, "yesInCourtProcess"],
    "form1[0].#subform[3].PtAIILine20_No2[0]" : [1, "noInCourtProcess"],

    "form1[0].#subform[3].ChildAlien3[0]" : [2, "foreignNumber"],
    "form1[0].#subform[3].ChildPassport3[0]": [2, "passportNumber"],
    "form1[0].#subform[3].ChildMarital3[0]" : [2, "maritalStatus"],
    "form1[0].#subform[3].ChildSSN3[0]" : [2, "socialSecurityNumber"],
    "form1[0].#subform[3].ChildLast3[0]" : [2, "lastName"],
    "form1[0].#subform[3].ChildFirst3[0]" : [2, "firstName"],
    "form1[0].#subform[3].ChildMiddle3[0]" : [2, "middleName"],
    "form1[0].#subform[3].ChildDOB3[0]" : [2, "birthday"],
    "form1[0].#subform[3].ChildCity3[0]" : [2, "birthPlace"],
    "form1[0].#subform[3].ChildNat3[0]" : [2, "presentNationality"],
    "form1[0].#subform[3].ChildRace3[0]" : [2, "race"],
    "form1[0].#subform[3].PtAIILine13_Specify3[0]" : [2, "currentLocation"],
    "form1[0].#subform[3].PtAIILine14_PlaceofLastEntry3[0]" : [2, "lastEntryPlace"],
    "form1[0].#subform[3].PtAIILine15_DateofLastEntry3[0]" : [2, "lastEntryDate"],
    "form1[0].#subform[3].PtAIILine16_I94Number3[0]" : [2, "i94Number"],
    "form1[0].#subform[3].PtAIILine17_StatusofLastAdmission3[0]": [2, "lastEntryStatus"],
    "form1[0].#subform[3].PtAIILine18_ChildCurrentStatus3[0]" : [2, "currentStatus"],
    "form1[0].#subform[3].PtAIILine19_ExpDateofAuthorizedStay3[0]" : [2, "statusExpirationDate"],
    "form1[0].#subform[3].CheckBox36_Gender[0]" : [2, "male"],
    "form1[0].#subform[3].CheckBox36_Gender[1]" : [2, "female"],
    "form1[0].#subform[3].CheckBox37[0]" : [2, "yesInAmerica"],
    "form1[0].#subform[3].CheckBox37[1]" : [2, "noInAmerica"],
    "form1[0].#subform[3].PtAIILine21_Yes3[0]" : [2, "yesInclude"],
    "form1[0].#subform[3].PtAIILine21_No3[0]" : [2, "noInclude"],
    "form1[0].#subform[3].PtAIILine20_Yes3[0]" : [2, "yesInCourtProcess"],
    "form1[0].#subform[3].PtAIILine20_No3[0]" : [2, "noInCourtProcess"],

    "form1[0].#subform[3].ChildAlien4[0]": [3, "foreignNumber"],
    "form1[0].#subform[3].ChildPassport4[0]" : [3, "passportNumber"],
    "form1[0].#subform[3].ChildMarital4[0]" : [3, "maritalStatus"],
    "form1[0].#subform[3].ChildSSN4[0]" : [3, "socialSecurityNumber"],
    "form1[0].#subform[3].ChildLast4[0]" : [3, "lastName"],
    "form1[0].#subform[3].ChildFirst4[0]" : [3, "firstName"],
    "form1[0].#subform[3].ChildMiddle4[0]" : [3, "middleName"],
    "form1[0].#subform[3].ChildDOB4[0]" : [3, "birthday"],
    "form1[0].#subform[3].ChildCity4[0]" : [3, "birthPlace"],
    "form1[0].#subform[3].ChildNat4[0]" : [3, "presentNationality"],
    "form1[0].#subform[3].ChildRace4[0]" : [3, "race"],
    "form1[0].#subform[3].PtAIILine13_Specify4[0]" : [3, "currentLocation"],
    "form1[0].#subform[3].PtAIILine14_PlaceofLastEntry4[0]" : [3, "lastEntryPlace"],
    "form1[0].#subform[3].PtAIILine15_DateofLastEntry4[0]" : [3, "lastEntryDate"],
    "form1[0].#subform[3].PtAIILine16_I94Number4[0]" : [3, "i94Number"],
    "form1[0].#subform[3].PtAIILine17_StatusofLastAdmission4[0]" : [3, "lastEntryStatus"],
    "form1[0].#subform[3].PtAIILine18_ChildCurrentStatus4[0]" : [3, "currentStatus"],
    "form1[0].#subform[3].PtAIILine19_ExpDateofAuthorizedStay4[0]" : [3, "statusExpirationDate"],
    "form1[0].#subform[3].CheckBox46_Gender[0]" : [3, "male"],
    "form1[0].#subform[3].CheckBox46_Gender[1]" : [3, "female"],
    "form1[0].#subform[3].CheckBox47[0]" : [3, "yesInAmerica"],
    "form1[0].#subform[3].CheckBox47[1]" : [3, "noInAmerica"],
    "form1[0].#subform[3].PtAIILine21_Yes4[0]" : [3, "yesInclude"],
    "form1[0].#subform[3].PtAIILine21_No4[0]" : [3, "noInclude"],
    "form1[0].#subform[3].PtAIILine20_Yes4[0]" : [3, "yesInCourtProcess"],
    "form1[0].#subform[3].PtAIILine20_No4[0]": [3, "noInCourtProcess"],
    
    "form1[0].#subform[12].TextField12[0]": [4, "lastName"],
    "form1[0].#subform[12].TextField12[1]": [4, "birthPlace"],
    "form1[0].#subform[12].TextField12[2]": [4, "firstName"],
    "form1[0].#subform[12].TextField12[3]": [4, "middleName"],
    "form1[0].#subform[12].DateTimeField14[0]": [4, "birthday"],
    "form1[0].#subform[12].TextField12[4]": [4, "presentNationality"],
    "form1[0].#subform[12].TextField12[5]": [4, "race"],
    "form1[0].#subform[12].ChildEntry5[0]": [4, "lastEntryPlace"],
    "form1[0].#subform[12].ChildExp5[0]": [4, "lastEntryDate"],
    "form1[0].#subform[12].ChildINum5[0]": [4, "i94Number"],
    "form1[0].#subform[12].ChildStatus5[0]": [4, "lastEntryStatus"],
    "form1[0].#subform[12].ChildCurrent5[0]": [4, "currentStatus"],
    "form1[0].#subform[12].ChildExpAuth5[0]": [4, "statusExpirationDate"],
    "form1[0].#subform[12].TextField12[6]": [4, "foreignNumber"],
    "form1[0].#subform[12].TextField12[7]": [4, "passportNumber"],
    "form1[0].#subform[12].TextField12[8]": [4, "maritalStatus"],
    "form1[0].#subform[12].TextField12[9]": [4, "socialSecurityNumber"],
    "form1[0].#subform[12].CheckBox12_Gender[0]": [4, "male"],
    "form1[0].#subform[12].CheckBox12_Gender[1]": [4, "female"],
    "form1[0].#subform[12].SuppA_CheckBox20[0]": [4, "yesInCourtProcess"],
    "form1[0].#subform[12].SuppA_CheckBox20[1]": [4, "noInCourtProcess"],
    "form1[0].#subform[12].SuppA_CheckBox21[0]": [4, "yesInclude"],
    "form1[0].#subform[12].SuppA_CheckBox21[1]": [4, "noInclude"],
    "form1[0].#subform[12].SuppLALine13_Specify[0]": [4, "currentLocation"],
    "form1[0].#subform[12].CheckBox57[0]": [4, "yesInAmerica"],
    "form1[0].#subform[12].CheckBox57[1]": [4, "noInAmerica"],

    "form1[0].#subform[12].TextField12[10]": [5, "lastName"],
    "form1[0].#subform[12].TextField12[11]": [5, "birthPlace"],
    "form1[0].#subform[12].TextField12[12]": [5, "firstName"],
    "form1[0].#subform[12].TextField12[13]": [5, "middleName"],
    "form1[0].#subform[12].DateTimeField14[1]": [5, "birthday"],
    "form1[0].#subform[12].TextField12[14]": [5, "presentNationality"],
    "form1[0].#subform[12].TextField12[15]": [5, "race"],
    "form1[0].#subform[12].ChildEntry6[0]": [5, "lastEntryPlace"],
    "form1[0].#subform[12].ChildExp6[0]": [5, "lastEntryDate"],
    "form1[0].#subform[12].ChildINum6[0]": [5, "i94Number"],
    "form1[0].#subform[12].ChildStatus6[0]": [5, "lastEntryStatus"],
    "form1[0].#subform[12].ChildCurrent6[0]": [5, "currentStatus"],
    "form1[0].#subform[12].ChildExpAuth6[0]": [5, "statusExpirationDate"],
    "form1[0].#subform[12].TextField12[16]": [5, "foreignNumber"],
    "form1[0].#subform[12].TextField12[17]": [5, "passportNumber"],
    "form1[0].#subform[12].TextField12[18]": [5, "maritalStatus"],
    "form1[0].#subform[12].TextField12[19]": [5, "socialSecurityNumber"],
    "form1[0].#subform[12].SuppAL12_CheckBox[0]": [5, "male"],
    "form1[0].#subform[12].SuppAL12_CheckBox[1]": [5, "female"],
    "form1[0].#subform[12].SuppALine20_CheckBox2[0]": [5, "yesInCourtProcess"],
    "form1[0].#subform[12].SuppALine20_CheckBox2[1]": [5, "noInCourtProcess"],
    "form1[0].#subform[12].SuppALine21_CheckBox[0]": [5, "yesInclude"],
    "form1[0].#subform[12].SuppALine21_CheckBox[1]": [5, "noInclude"],
    "form1[0].#subform[12].SuppLALine13_Specify2[0]": [5, "currentLocation"],
    "form1[0].#subform[12].SuppAL13_CheckBox[0]": [5, "yesInAmerica"],
    "form1[0].#subform[12].SuppAL13_CheckBox[1]": [5, "noInAmerica"],
  }

}